# nginx.conf

worker_processes 1;

events {
    worker_connections 1024;
}

# Define microservices 
http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    # Upstream for Keycloak
    upstream keycloak {
        server keycloak:8888;  # This should match the service name and port in your Docker Compose file
    }

    upstream dapm.clientapi {
        server dapm.clientapi:8080;  # This should match the service name and port in your Docker Compose file
    }

    #server keycloak
    server {
        listen 8888;
        server_name localhost;
        # Forward requests to Keycloak
        location / {
            proxy_pass http://keycloak;
            proxy_set_header Host $host;
        }
        
        # Example for other services (e.g., dapm.clientapi)
        # location /api/ {
        #     proxy_pass http://dapm.clientapi:8080;
        #     proxy_set_header Host $host;
        #     proxy_set_header X-Real-IP $remote_addr;
        #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        #     proxy_set_header X-Forwarded-Proto $scheme;
        # }
    }

    #server dapm.clientapi
    server {
        listen 5000;
        server_name localhost;
        # Forward requests to dapm.clientapi
        location / {
            proxy_pass http://dapm.clientapi;
            proxy_set_header Host $host;
        }
    }
}
