events {}

http {
  server {
    listen 80;

    # Handle OAuth2 Proxy callbacks
    location /oauth2/ {
      proxy_pass       http://oauth2-proxy:4180;
      proxy_set_header Host              $host;
      proxy_set_header X-Real-IP         $remote_addr;
      proxy_set_header X-Scheme          $scheme;
      proxy_connect_timeout              1s;
      proxy_send_timeout                 30s;
      proxy_read_timeout                 30s;
    }

    # Protect /clientapi
    location /clientapi/ {
      auth_request /oauth2/auth;
      error_page 401 = @oauth2_sign_in;

      # Pass user info to the backend
      auth_request_set $user   $upstream_http_x_auth_request_user;
      proxy_set_header X-User  $user;

      proxy_pass http://dapm.clientapi:8080;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    # Protect /peerapi
    location /peerapi/ {
      auth_request /oauth2/auth;
      error_page 401 = @oauth2_sign_in;

      # Pass user info to the backend
      auth_request_set $user   $upstream_http_x_auth_request_user;
      proxy_set_header X-User  $user;

      proxy_pass http://dapm.peerapi:8080;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    # Redirect unauthenticated users to OAuth2 Proxy
    location @oauth2_sign_in {
      return 302 /oauth2/start?rd=$request_uri;
    }
  }
}
