version: '3.8'
services:
  react:
    container_name: react-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV_FILE: ${ENV_FILE:-.env}
    ports:
      - "3000:80"  
    volumes:
      - ./${ENV_FILE:-.env}:/app/.env 
    restart: unless-stopped
