name: .NET

on:
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-back-end-in-docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Start backend containers
      run: docker compose -f "./DAPM/docker-compose.yml" up -d --build

  build-front-end-in-docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: build-back-end-in-docker  # Ensure frontend builds after backend

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Start frontend containers
      run: docker compose -f "./DAPM-Frontend/docker-compose.yml" up -d --build

  e2e-test:
    runs-on: ubuntu-latest
    needs: [build-back-end-in-docker, build-front-end-in-docker]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ./EndToEndTest/EndToEndTest.sln

    - name: Build
      run: dotnet build ./EndToEndTest/EndToEndTest.sln --no-restore

    - name: Run tests in Docker container
      run: |
        docker-compose -f ./DAPM/docker-compose.yml run --rm dapm.clientapiendtoendtest 

  stop-containers:
    runs-on: ubuntu-latest
    needs: e2e-test  # Stop containers after tests have run

    steps:
    - name: Stop backend containers
      run: docker compose -f "./DAPM/docker-compose.yml" down
    - name: Stop frontend containers
      run: docker compose -f "./DAPM-Frontend/docker-compose.yml" down
