name: build-and-test

on:
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-and-test-back-end-in-docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start containers
      run: docker compose -f "./DAPM/docker-compose.yml" up -d --build

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ./DAPM/TestResults/*.trx
    
    - name: Stop containers
      run: docker compose -f "./DAPM/docker-compose.yml" down

  build-front-end-in-docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start containers
      run: docker compose -f "./DAPM-Frontend/docker-compose.yml" up -d --build
    
    - name: Stop containers
      run: docker compose -f "./DAPM-Frontend/docker-compose.yml" down
